networks:
  mvp-widgets:
    driver: bridge
name: app
services:
  php-fpm:
    build:
      context: docker/php-fpm-74
      dockerfile: Dockerfile
    container_name: php-fpm
    restart: always
    working_dir: /var/www
    ports:
      - "9000:9000"
    networks:
      - mvp-widgets
    volumes:
      - ./:/var/www

  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - php-fpm
    networks:
      - mvp-widgets
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf